# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unionproto.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10unionproto.proto\x1a\x0cnanopb.proto\"\x19\n\x08MsgType1\x12\r\n\x05value\x18\x01 \x03(\x05\")\n\x08MsgType2\x12\r\n\x05value\x18\x01 \x03(\x05\x12\x0e\n\x06led_on\x18\x02 \x02(\x08\"\xea\x01\n\x08MsgType3\x12\x0e\n\x06value1\x18\x01 \x02(\x05\x12\x0e\n\x06value2\x18\x02 \x02(\x05\x12\x0e\n\x06value3\x18\x03 \x02(\x05\x12\x0e\n\x06value4\x18\x04 \x02(\x05\x12\x0e\n\x06value5\x18\x05 \x02(\x05\x12\x0e\n\x06value6\x18\x06 \x02(\x05\x12\x0e\n\x06value7\x18\x07 \x02(\x05\x12\x0c\n\x04str1\x18\x08 \x02(\t\x12\x0c\n\x04str2\x18\t \x02(\t\x12\x0c\n\x04str3\x18\n \x02(\t\x12\x0c\n\x04str4\x18\x0b \x02(\t\x12\x0c\n\x04str5\x18\x0c \x02(\t\x12\x0c\n\x04str6\x18\r \x02(\t\x12\x0c\n\x04str7\x18\x0e \x02(\t\x12\x0c\n\x04str8\x18\x0f \x02(\t\"\x95\x01\n\x0cOneOfMessage\x12\x14\n\x0clucky_number\x18\x01 \x02(\x05\x12\x0b\n\x03str\x18\x02 \x02(\t\x12\x19\n\x04msg1\x18\x03 \x01(\x0b\x32\t.MsgType1H\x00\x12\x19\n\x04msg2\x18\x04 \x01(\x0b\x32\t.MsgType2H\x00\x12\x19\n\x04msg3\x18\x05 \x01(\x0b\x32\t.MsgType3H\x00:\x06\x92?\x03\xb0\x01\x01\x42\t\n\x07payload')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unionproto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ONEOFMESSAGE']._options = None
  _globals['_ONEOFMESSAGE']._serialized_options = b'\222?\003\260\001\001'
  _globals['_MSGTYPE1']._serialized_start=34
  _globals['_MSGTYPE1']._serialized_end=59
  _globals['_MSGTYPE2']._serialized_start=61
  _globals['_MSGTYPE2']._serialized_end=102
  _globals['_MSGTYPE3']._serialized_start=105
  _globals['_MSGTYPE3']._serialized_end=339
  _globals['_ONEOFMESSAGE']._serialized_start=342
  _globals['_ONEOFMESSAGE']._serialized_end=491
# @@protoc_insertion_point(module_scope)
