import sys, os

# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'DAS'
copyright = '2023, Vincent Ho'
author = 'Vincent Ho'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

sys.path.append("/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-package/breathe")

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_sitemap',
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx_sitemap',
    'sphinx.ext.inheritance_diagram',
    'breathe'
]

# Assuming the conf.py is located within docs/source directory under the root directory
ROOT_DIR = os.path.abspath(os.path.join(__file__, "../../.."))
print(f"ROOT_DIR={ROOT_DIR}")

XML_DIR = os.path.join(ROOT_DIR, "build", "docs","doxygen","xml")
print(f"XML_DIR={XML_DIR}")
# Check if the XML dir exists first
if (not os.path.isdir(XML_DIR)):
    print(f"Error in conf.py: {XML_DIR} does not exist. Therefore, can't generate docs with Sphinx, please make sure it is generated by Doxygen first.")
    sys.exit()


breathe_projects = {"DAS": XML_DIR}

breathe_default_project = "DAS"


templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
highlight_language = 'c++'
html_static_path = ['_static']
html_baseurl = os.path.join(ROOT_DIR,"build","docs","sphinx","html","index.html")
breathe_projects_source = {
    "auto" : (os.path.join(ROOT_DIR, "hello_world_usb"), ["picow_hello_world_usb.cpp"])
}


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    
    'logo_only': False,

    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}
# html_logo = ''
# github_url = ''
# html_baseurl = ''


